# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PlanOgolny
                                 A QGIS plugin
 This plugin create vector layer with predefined fields' names in the attribute table. 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-03-24
        copyright            : (C) 2025 by Aldona Bełc
        email                : aldonabelc@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PlanOgolny class from file PlanOgolny.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .plan_ogolny import PlanOgolny
    return PlanOgolny(iface)